name: Echo Workflow

on:
  push:
    branches:
      - feature
  workflow_dispatch:

jobs:
  echo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Echo message
        run: echo "🚀 Hello from GitHub Actions!"
